guest=['steve jobs', 'lee kun-hee', 'tim cook']
print(f"Welcome {guest[0].title()}")
print(f"안녕하세요 {guest[1].title()}")
print(f"Welcome {guest[2].title()}")
print(f"{guest[0].title()} told me that he can't to visit")
guest.remove("steve jobs")
print(f"안녕하세요 {guest[0].title()}")
print(f"Welcome {guest[1].title()}")
print(f"{guest}, I found more big table.")
guest.insert(0,"son masayoshi")
guest.insert(1,"super mario")
guest.append("donald trump")
print(guest)
print("new table looks like too weak so only two person can visit.")
poped_person=guest.pop()
print(f"So sorry to say this to you, {poped_person.title()}. there is no empty seat for you.")
print(guest)
poped_person=guest.pop()
print(f"So sorry to say this to you, {poped_person.title()}. there is no empty seat for you.")
poped_person=guest.pop()
print(f"So sorry to say this to you, {poped_person.title()}. there is no empyt seat for you.")
print(guest)
print(f"I have seat for you, {guest[0].title()}.")
print(f"I have seat for you, {guest[1].title()}.")
del guest[0]
print(guest)
del guest[0]
print(guest)